### ISSUE TITLE
Stream could not be initialized! - An unexpected server error occurred..........

### ISSUE THREAD

**Issue by swapnil2sutar** [ConnectedCommunities/humhub-modules-questionanswer#50]
One of my user is facing this issue who have also admin access. After login his dashboard shows **Stream could not be initialized** & at the bottom **An unexpected server error occurred. If this keeps happening, please contact a site administrator.** Also when I expand the toggle error following error is shown
`{ "url": "/index.php?r=dashboard%2Fdashboard%2Fstream&mode=normal", "status": 500, "response": { "name": "Internal Server Error", "message": "An internal server error occurred.", "code": 0, "status": 500 }, "textStatus": "error", "dataType": "json", "xhr": { "readyState": 4, "responseText": "{\"name\":\"Internal Server Error\",\"message\":\"An internal server error occurred.\",\"code\":0,\"status\":500}", "responseJSON": { "name": "Internal Server Error", "message": "An internal server error occurred.", "code": 0, "status": 500 }, "status": 500, "statusText": "Internal Server Error" }, "name": "Internal Server Error", "message": "An internal server error occurred.", "code": 0, "error": {}, "errorThrown": "Internal Server Error", "validationError": false }`

**Also Log entries have following errors:**
`$_GET = [ 'r' => 'dashboard/dashboard/stream' 'mode' => 'normal' 'StreamQuery' => [ 'sort' => 'c' 'from' => '0' 'limit' => '4' 'suppressionsOnly' => 'false' ] ] $_SERVER = [ 'LSPHP_ENABLE_USER_INI' => 'on' 'PATH' => '/usr/local/bin:/usr/bin:/bin' 'TEMP' => '/tmp' 'TMP' => '/tmp' 'TMPDIR' => '/tmp' 'HTTP_ACCEPT' => 'application/json, text/javascript, */*; q=0.01' 'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br' 'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.8' 'HTTP_CONNECTION' => 'keep-alive' 'CONTENT_LENGTH' => '0' 'HTTP_COOKIE' => '_csrf=01d8b30942751c3ec0792d394a79ccb8c1f624e7593ec4a1bed69951f00a15fda%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22%08%BE%CF%B8%02%92R%AB%C9%DFi-%80%F6%DB3%09%5C%26%B5%8B%EFT%F3%7F%F4.o%99%5B8%A8%22%3B%7D; PHPSESSID=lo10pscuaomueb57so7sn5ttf7; pm_getting-started-panel=expanded; _identity=5efaac265a124a1743e550ee035a16ba53f3c9183320021dbfccb3f4824f6350a%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A50%3A%22%5B1%2C%222df62a1a-3b49-4d85-8ffa-1c23c92105f6%22%2C2592000%5D%22%3B%7D' 'HTTP_HOST' => 'decode.onlinesales.ai' 'HTTP_REFERER' => 'https://decode.onlinesales.ai/index.php?r=dashboard%2Fdashboard' 'HTTP_USER_AGENT' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36' 'HTTP_X_CSRF_TOKEN' => 'eAZSMGBaqsMWekIYMFKfaJjGDSlu6Rn1mf7J2CyD4zpwuJ2IYsj4aN-lKzWwpERbkZornOUGTQbmCue3tdjbkg==' 'HTTP_X_REQUESTED_WITH' => 'XMLHttpRequest' 'UNIQUE_ID' => 'WeS@hmcVOkIABH@Oq3wAAAAQ' 'HTTPS' => 'on' 'SSL_TLS_SNI' => 'decode.onlinesales.ai' 'SERVER_SIGNATURE' => '' 'SERVER_SOFTWARE' => 'Apache Phusion_Passenger/4.0.10 mod_bwlimited/1.4' 'SERVER_NAME' => 'decode.onlinesales.ai' 'SERVER_ADDR' => '103.21.58.66' 'SERVER_PORT' => '443' 'REMOTE_ADDR' => '49.248.126.66' 'DOCUMENT_ROOT' => '/home3/knowladv/public_html/decode' 'SERVER_ADMIN' => 'webmaster@decode.onlinesales.ai' 'SCRIPT_FILENAME' => '/home3/knowladv/public_html/decode/index.php' 'REMOTE_PORT' => '48919' 'SERVER_PROTOCOL' => 'HTTP/1.1' 'REQUEST_METHOD' => 'GET' 'QUERY_STRING' => 'r=dashboard%2Fdashboard%2Fstream&mode=normal&StreamQuery%5Bsort%5D=c&StreamQuery%5Bfrom%5D=0&StreamQuery%5Blimit%5D=4&StreamQuery%5BsuppressionsOnly%5D=false' 'REQUEST_URI' => '/index.php?r=dashboard%2Fdashboard%2Fstream&mode=normal&StreamQuery%5Bsort%5D=c&StreamQuery%5Bfrom%5D=0&StreamQuery%5Blimit%5D=4&StreamQuery%5BsuppressionsOnly%5D=false' 'SCRIPT_NAME' => '/index.php' 'PHP_SELF' => '/index.php' 'REQUEST_TIME_FLOAT' => 1508163206.5469 'REQUEST_TIME' => 1508163206 ]

exception 'yii\base\ErrorException' with message 'Trying to get property of non-object' in /home/knowladv/public_html/decode/protected/modules/questionanswer/widgets/views/searchResult_answer.php:27 Stack trace: #0 /home/knowladv/public_html/decode/protected/modules/questionanswer/widgets/views/searchResult_answer.php(27): yii\base\ErrorHandler->handleError(8, 'Trying to get p...', '/home/knowladv/...', 27, Array) #1 /home/knowladv/public_html/decode/protected/vendor/yiisoft/yii2/base/View.php(330): require('/home/knowladv/...') #2 /home/knowladv/public_html/decode/protected/vendor/yiisoft/yii2/base/View.php(250): yii\base\View->renderPhpFile('/home/knowladv/...', Array) #3 /home/knowladv/public_html/decode/protected/vendor/yiisoft/yii2/base/View.php(152): yii\base\View->renderFile('/home/knowladv/...', Array, Object(humhub\modules\questionanswer\widgets\AnswerWallEntryWidget)) #4 /home/knowladv/public_html/decode/protected/vendor/yiisoft/yii2/base/Widget.php(234): yii\base\View->render('searchResult_an...', Array, Object(humhub\modules\questionanswer\widgets\AnswerWallEntryWidget)) #5 /home/knowladv/public_html/decode/protected/modules/questionanswer/widgets/AnswerWallEntryWidget.php(44): yii\base\Widget->render('searchResult_an...', Array) #6 /home/knowladv/public_html/decode/protected/humhub/modules/content/widgets/WallEntry.php(261): humhub\modules\questionanswer\widgets\AnswerWallEntryWidget->run() #7 /home/knowladv/public_html/decode/protected/humhub/modules/content/widgets/WallEntry.php(225): humhub\modules\content\widgets\WallEntry->getWallEntryViewParams() #8 /home/knowladv/public_html/decode/protected/humhub/modules/content/components/ContentActiveRecord.php(270): humhub\modules\content\widgets\WallEntry->renderWallEntry() #9 /home/knowladv/public_html/decode/protected/humhub/modules/stream/actions/Stream.php(319): humhub\modules\content\components\ContentActiveRecord->getWallOut(Array) #10 /home/knowladv/public_html/decode/protected/humhub/modules/stream/actions/Stream.php(353): humhub\modules\stream\actions\Stream::renderEntry(Object(humhub\modules\questionanswer\models\Answer), false) #11 /home/knowladv/public_html/decode/protected/humhub/modules/stream/actions/Stream.php(233): humhub\modules\stream\actions\Stream::getContentResultEntry(Object(humhub\modules\content\models\Content)) #12 [internal function]: humhub\modules\stream\actions\Stream->run() #13 /home/knowladv/public_html/decode/protected/vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array) #14 /home/knowladv/public_html/decode/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\Action->runWithParams(Array) #15 /home/knowladv/public_html/decode/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('stream', Array) #16 /home/knowladv/public_html/decode/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('dashboard/dashb...', Array) #17 /home/knowladv/public_html/decode/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request)) #18 /home/knowladv/public_html/decode/index.php(25): yii\base\Application->run() #19 {main}`

I have attached screenshots for the same.

Please help to debug

![humhub_dashboard](https://user-images.githubusercontent.com/16332853/31650643-f9182704-b335-11e7-8a20-5256beae5a34.png)

**Comment by swapnil2sutar** [comment]
Issue has been resolved, I have disabled Q&A module, then tried by  `php yii integirty/run` & it worked perfectly.  Thanks for all your help @Felli .
