### ISSUE TITLE
Issue when I click "unanswered questions" and "picked for you"

### ISSUE THREAD

**Issue by exocode** [ConnectedCommunities/humhub-modules-questionanswer#56]
what can cause this issue?

Thank you

```
yii\base\ErrorException: Undefined variable: contentContainer in /var/www/html/humhub/protected/modules/questionanswer/views/question/index.php:34
Stack trace:
#0 /var/www/html/humhub/protected/modules/questionanswer/views/question/index.php(34): yii\base\ErrorHandler->handleError(8, 'Undefined varia...', '/var/www/html/h...', 34, Array)
#1 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/View.php(336): require('/var/www/html/h...')
#2 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile('/var/www/html/h...', Array)
#3 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/var/www/html/h...', Array, Object(humhub\modules\questionanswer\controllers\QuestionController))
#4 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(384): yii\base\View->render('index', Array, Object(humhub\modules\questionanswer\controllers\QuestionController))
#5 /var/www/html/humhub/protected/modules/questionanswer/controllers/QuestionController.php(302): yii\base\Controller->render('index', Array)
#6 [internal function]: humhub\modules\questionanswer\controllers\QuestionController->actionUnanswered()
#7 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#8 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#9 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('unanswered', Array)
#10 /var/www/html/humhub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('questionanswer/...', Array)
#11 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request))
#12 /var/www/html/humhub/index.php(25): yii\base\Application->run()
#13 {main}
```

**Comment by baoc75** [comment]
A pull request has been made #61

**Comment by rafawrm** [comment]
I have this bug too.
